INSERT INTO "Customer" VALUES(1,'3044987','บจก. ตระกูลเศรษฐี','','',NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO "CustomerSurveySite" VALUES(1,1,'139 ถ.สายวังสะพุง-หนองเขียด ต.วังสะพุง อ.วังสะพุง จ.เลย','0812617500',NULL,13.761228,100.552883,NULL,1);
INSERT INTO "CustomerSurveySite" VALUES(2,1,'218 หมู่ 4 ถ.สายวังสะพุง-หนองเขียด ต.วังสะพุง อ.วังสะพุง จ.เลย',NULL,NULL,13.75681,100.56447,NULL,1);
INSERT INTO "CustomerSurveySite" VALUES(3,1,'ซ.ข้างโรงพยาบาลวังสะพุง ถ.สายวังสะพุง-หนองเขียด ต.วังสะพุง อ.วังสะพุง จ.เลย',NULL,NULL,13.740427,100.556273,NULL,1);


INSERT INTO "InspectType" VALUES(1,'Cluster');
INSERT INTO "InspectType" VALUES(2,'Package');
INSERT INTO "InspectType" VALUES(3,'Adhoc');

INSERT INTO "productGroup" VALUES(1,'ข้าว',250.50);

INSERT INTO "Product" VALUES(1,1,'ลูกเดือย');
INSERT INTO "Product" VALUES(1,2,'มันสำปะหลัง');
INSERT INTO "Product" VALUES(1,3,'ข้าวโพด');

INSERT INTO "ProductAmountUnit" VALUES (1, 'ตัน');
INSERT INTO "ProductAmountUnit" VALUES (2, 'กระสอบ');
INSERT INTO "ProductAmountUnit" VALUES (3, 'กิโลกรัม');
INSERT INTO "ProductAmountUnit" VALUES (4, 'กล่อง');
INSERT INTO "ProductAmountUnit" VALUES (5, 'ปี๊ป');
INSERT INTO "ProductAmountUnit" VALUES (6, 'ถุง');
INSERT INTO "ProductAmountUnit" VALUES (7, 'ชิ้น');
INSERT INTO "ProductAmountUnit" VALUES (8, 'หีบ');


INSERT INTO "JobRequest" VALUES (1, 1, 1, null, null, null, '56/02/017');

INSERT INTO "Task" VALUES (1, '56/02/017', 1, 1, 4, 1, 0, '2013-09-22', '10:00','13:00',-1,-1, null, null,0,0,null,null,0);
INSERT INTO "Task" VALUES (2, '56/02/018', 1, 2, 4, 1, 0, '2013-10-14', '10:00','13:00',-1,-1, null, null,0,0,null,null,0);
INSERT INTO "Task" VALUES (3, '56/02/019', 1, 3, 4, 1, 0, '2013-11-10', '10:00','13:00', -1,-1,null, null,0,0,null,null,0);


INSERT INTO "InspectDataGroupType" VALUES (1, 'อาคาร/สิ่งปลูกสร้าง', X'4e');
INSERT INTO "InspectDataGroupType" VALUES (2, 'ทางเข้า', X'4e');
INSERT INTO "InspectDataGroupType" VALUES (3, 'แนวเขตที่ดิน', X'4e');
INSERT INTO "InspectDataGroupType" VALUES (4, 'อาคารเก็บสินค้า', X'4e');
INSERT INTO "InspectDataGroupType" VALUES (5, 'มุมกล้อง', X'4e');
INSERT INTO "InspectDataGroupType" VALUES (6, 'ภาชนะบรรจุ', X'59');
INSERT INTO "InspectDataGroupType" VALUES (7, 'เทกอง', X'59');

INSERT INTO "InspectDataItem" VALUES (1, 1, 'สำนักงาน', null, null,  'obj_office.svg');
INSERT INTO "InspectDataItem" VALUES (2, 1, 'ป้อมยาม', null, null,  'obj_security.svg');
INSERT INTO "InspectDataItem" VALUES (3, 1, 'เครื่องสีข้าว', null, null,  'obj_grind.svg');
INSERT INTO "InspectDataItem" VALUES (4, 1, 'เครื่องชั่งน้ำหนัก', null, null,  'obj_scale.svg');
INSERT INTO "InspectDataItem" VALUES (5, 1, 'เตาอบ', null, null,  'obj_oven.svg');
INSERT INTO "InspectDataItem" VALUES (6, 1, 'โกดัง', null, null,  'obj_warehouse.svg');
INSERT INTO "InspectDataItem" VALUES (7, 1, 'ลานตาก', null, null,  'obj_yard.svg');
INSERT INTO "InspectDataItem" VALUES (8, 1, 'ไซโลสี่เหลี่ยม(ปูน)', null, null,  'obj_silobrick.svg');
INSERT INTO "InspectDataItem" VALUES (9, 1, 'ไซโลสี่เหลี่ยม(เหล็ก)', null, null,  'obj_silosteel.svg');
INSERT INTO "InspectDataItem" VALUES (10, 1, 'สตาร์บิน', null, null,  'obj_silostar.svg');
INSERT INTO "InspectDataItem" VALUES (11, 1, 'ไซโลทรงกระบอก', null, null, 'obj_silocan.svg');
INSERT INTO "InspectDataItem" VALUES (12, 1, 'อาคารไม่มีผนัง(หลังคาคลุม)', null, null,  'obj_nowall.svg');
INSERT INTO "InspectDataItem" VALUES (13, 2, 'ทางเข้าบริเวณ', null, null,  'obj_enterbound.svg');
INSERT INTO "InspectDataItem" VALUES (14, 2, 'ทิศทางการเข้า', null, null,  'obj_enterbuilding.svg');
INSERT INTO "InspectDataItem" VALUES (15, 3, 'แนวเขตที่ดิน', null, null,  'obj_bound.svg');
INSERT INTO "InspectDataItem" VALUES (16, 4, 'โกดัง', null, null,  'obj_warehouseout.svg');
INSERT INTO "InspectDataItem" VALUES (17, 4, 'ไซโลสี่เหลี่ยม', null, null,  'obj_silosqr.svg');
INSERT INTO "InspectDataItem" VALUES (18, 4, 'ไซโลทรงกระบอก', null, null,  'obj_siloout.svg');
INSERT INTO "InspectDataItem" VALUES (19, 4, 'ลานตาก', null, null,  'obj_yardsqr.svg');
INSERT INTO "InspectDataItem" VALUES (20, 4, 'สตาร์บิน', null, null,  'obj_warehouseout.svg');
INSERT INTO "InspectDataItem" VALUES (21, 5, 'มุมกล้อง', null, null,  'obj_camera.svg');
INSERT INTO "InspectDataItem" VALUES (22, 6, 'ถุงจัมโบ้', 3, 'w*d*h', 'obj_jumbo.svg');
INSERT INTO "InspectDataItem" VALUES (23, 6, 'กระสอบป่าน', 3, 'w*d*h',  'obj_hemp.svg');
INSERT INTO "InspectDataItem" VALUES (24, 6, 'กระสอบหรือถุงพลาสติก', 3, 'w*d*h',  'obj_hemp.svg');
INSERT INTO "InspectDataItem" VALUES (25, 6, 'ถังเหล็ก', 3, 'w*d*h',  'obj_can.svg');
INSERT INTO "InspectDataItem" VALUES (26, 6, 'ลังหรือกล่อง', 3, 'w*d*h',  'obj_yardout.svg');
INSERT INTO "InspectDataItem" VALUES (28, 7, 'เทกองแบบภูเขา', 3, '(w*d*h*0.785)/3',  'obj_bulk.svg');
INSERT INTO "InspectDataItem" VALUES (29, 7, 'เทกองแบบสันเขา', 3, '((w-d)*d*h/2)+((d*d*h*0.785)/3)',  'obj_ridge.svg');
INSERT INTO "InspectDataItem" VALUES (30, 7, 'เทกองแบบพิรามิด', 3, 'w*d*h/3',  'obj_pyramid.svg');
INSERT INTO "InspectDataItem" VALUES (31, 7, 'เทกองแบบหลังคาตึก', 3, '((w-d)*d*h/2)+(d*d*h/2)',  'obj_roof.svg');
INSERT INTO "InspectDataItem" VALUES (32, 7, 'เทกองแบบทางลาด', 3, 'w*d*h/2',  'obj_ramp.svg');
INSERT INTO "InspectDataItem" VALUES (33, 7, 'เทกองแบบภูเขาชิดมุม', 4, '((w*2)*(d*2)*0.785*h/3)/(a/360)', 'obj_bulkangle.svg');
INSERT INTO "InspectDataItem" VALUES (34, 7, 'เทกองแบบพิรามิดชิดมุม', 3, '(w*d*h)/5', 'obj_bin_angle.svg');
INSERT INTO "InspectDataItem" VALUES (35, 7, 'เทกองในกะบะ', 3, 'w*d*h', 'obj_bin.svg');


INSERT INTO "TaskControlTemplate" VALUES (1, 1, 'SimpleText');
INSERT INTO "TaskControlTemplate" VALUES (2, 2, 'RadioSingleChoiceList');
INSERT INTO "TaskControlTemplate" VALUES (3, 3, 'CheckboxMultiChoiceList');
INSERT INTO "TaskControlTemplate" VALUES (4, 4, 'RadioboxMatrix');
INSERT INTO "TaskControlTemplate" VALUES (5, 5, 'Slider');
INSERT INTO "TaskControlTemplate" VALUES (6, 6, 'Sortable');


INSERT INTO "TaskFormTemplate" VALUES (1, 2, 1, 1, 'What is your name?', null, 'Microsoft,Google,Apple', null, null, null, null, 'test', X'32302f30372f32303133');
INSERT INTO "TaskFormTemplate" VALUES (1, 3, 2, 1, 'What is your first name?', null, 'ABC,DEF,GHI,JKL', null, null, null, null, 'test', X'32302f30372f32303133');
INSERT INTO "TaskFormTemplate" VALUES (1, 2, 3, 1, 'What is apple inc?', null, 'Good company,Bad Company', null, null, null, null, 'test', X'32302f30372f32303133');
INSERT INTO "TaskFormTemplate" VALUES (1, 1, 4, 1, 'What is my name?', null, null, null, null, null, null, 'test', X'32302f30372f32303133');
INSERT INTO "TaskFormTemplate" VALUES (1, 4, 5, 1, 'What the best company', 'Fail,Poor,Average,Good,Excellence', 'Microsoft,Apple,Google,Acer', null, null, null, null, 'test', X'32302f30372f32303133');
INSERT INTO "TaskFormTemplate" VALUES (1, 5, 6, 1, 'Please show scroll', null, 'Microsoft,Apple,Google,Acer', null, 0, 100, 10, 'test', X'32302f30372f32303133');



INSERT INTO "Team" VALUES (1, 'N01', 'ทีมเหนือ 1', '83cc7d16-d60e-31cc-a9ef-094770ebebc0', 'เชียงราย', '08-5111-6762');
INSERT INTO "Team" VALUES (2, 'N02', 'ทีมเหนือ 2', null, 'พิษณุโลก', '08-5111-6777');
INSERT INTO "Team" VALUES (3, 'N03', 'ทีมเหนือ 3', null, 'เชียงราย', '08-5111-6776');
INSERT INTO "Team" VALUES (4, 'N04', 'ทีมเหนือ 4', null, 'เชียงใหม่', '08-5111-6764');
INSERT INTO "Team" VALUES (5, 'N05', 'ทีมเหนือ 5', null, 'กำแพงเพชร', '08-5111-6751');
INSERT INTO "Team" VALUES (6, 'N06', 'ทีมเหนือ 6', null, 'แม่สอด', '08-5111-6758');
INSERT INTO "Team" VALUES (7, 'N07', 'ทีมเหนือ 7', null, 'กำแพงเพชร', ' 08-5111-6756');
INSERT INTO "Team" VALUES (8, 'N08', 'ทีมเหนือ ​8', null, 'พิษณุโลก', '08-5111-8857');
INSERT INTO "Team" VALUES (9, 'C01', 'ทีมกลาง 1', null, 'นว1 กำแพงเพชร', '08-5111-6767');
INSERT INTO "Team" VALUES (10, 'C02', 'ทีมกลาง 2', null, 'นครสวรรค์ 2', '08-5111-6771');
INSERT INTO "Team" VALUES (11, 'C03', 'ทีมกลาง 3', null, 'นครสวรรค์ 3', '08-8874-3207');
INSERT INTO "Team" VALUES (12, 'C05', 'ทีมกลาง 5', null, 'สุพรรณบุรี 1', '08-5111-6769');
INSERT INTO "Team" VALUES (13, 'C06', 'ทีมกลาง 6', null, 'สพ2 กำแพงแสน', '08-5111-6770');
INSERT INTO "Team" VALUES (14, 'C07', 'ทีมกลาง 7', null, 'สุพรรณบุรี 3', '08-2450-7267');
INSERT INTO "Team" VALUES (15, 'C08', 'ทีมกลาง 8', null, 'ชัยนาท', '08-5111-6768');
INSERT INTO "Team" VALUES (16, 'C09', 'ทีมกลาง 9', null, 'สระบุรี', '08-5111-6773');
INSERT INTO "Team" VALUES (17, 'C10', 'ทีมกลาง 10', null, 'สระบุรี', '08-5111-6754');
INSERT INTO "Team" VALUES (18, 'C12', 'ทีมกลาง 12', null, 'อยุธยา', '08-5111-6760');
INSERT INTO "Team" VALUES (19, 'C13', 'ทีมกลาง 13', null, 'เพชรบูรณ์ ', '08-2450-7228');
INSERT INTO "Team" VALUES (20, 'C14', 'ทีมกลาง 14', null, 'เพชรบูรณ์', '08-5111-6766');
INSERT INTO "Team" VALUES (21, 'C15', 'ทีมกลาง 15', null, 'นครสวรรค์4(ชัยนาท)', '08-5111-6759');
INSERT INTO "Team" VALUES (22, 'I01', 'ทีมอิสาน 1', null, 'นครราชสีมา', '08-5111-6753');
INSERT INTO "Team" VALUES (23, 'I02', 'ทีมอิสาน 2', null, 'อุดรธานี', '08-8874-3206');
INSERT INTO "Team" VALUES (24, 'I03', 'ทีมอิสาน 3', null, 'สุรินทร์', '08-8022-4750');
INSERT INTO "Team" VALUES (25, 'I04', 'ทีมอิสาน 4', null, 'ขอนแก่น', '08-8874-3204');
INSERT INTO "Team" VALUES (26, 'I05', 'ทีมอิสาน 5', null, 'อำนาจเจริญ', '08-5111-6775');
INSERT INTO "Team" VALUES (27, 'I06', 'ทีมอิสาน 6', null, 'ศรีสะเกษ', '08-8022-4751');
INSERT INTO "Team" VALUES (28, 'I09', 'ทีมอิสาน 9', null, 'บุรีรัมย์', '08-5111-6750');
INSERT INTO "Team" VALUES (29, 'I10', 'ทีมอิสาน 10', null, 'เลย', '08-5111-6761');

INSERT INTO "Role" VALUES (1, 'System Administrator');
INSERT INTO "Role" VALUES (2, 'User');
INSERT INTO "Role" VALUES (3, 'Customer Service');
INSERT INTO "Role" VALUES (4, 'Operation Manager');
INSERT INTO "Role" VALUES (5, 'Operation');

INSERT INTO "Employee" VALUES (1, 4, 'คุณ', 'สมชาย', 'ศรีใส', null, null, null, ' ', null, 'สมชาย', 1234, null, null);
INSERT INTO "Employee" VALUES (2, 4, 'คุณ', 'วัชรดุล', 'ขวัญแดง', null, null, null, ' ', null, 'วัชรดุล', 1234, null, null);
INSERT INTO "Employee" VALUES (3, 4, 'คุณ', 'พชรชัย', 'วัฒนสุภานนท์', null, null, null, '08-5111-6764', null, 'พชรชัย', 1234, null, null);
INSERT INTO "Employee" VALUES (4, 4, 'คุณ', 'จีรัชญ์พัฒน์', 'ธะเศรษฐ', null, null, null, '08-5111-6765', null, 'จีรัชญ์พัฒน์', 1234, null, null);
INSERT INTO "Employee" VALUES (5, 2, 'คุณ', 'ภาสกร', 'สกุลซิ้มถาวร', null, null, null, '08-5111-6766', null, 'ภาสกร', 1234, null, null);
INSERT INTO "Employee" VALUES (6, 2, 'คุณ', 'ปรีดา', 'เบ็ญจวรรณ', null, null, null, '08-5111-6767', null, 'ปรีดา', 1234, null, null);
INSERT INTO "Employee" VALUES (7, 2, 'คุณ', 'ภัทรศักดิ์', 'บุญสม', null, null, null, '08-5111-6768', null, 'ภัทรศักดิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (8, 2, 'คุณ', 'พเนต', 'เจริญเกตุ', null, null, null, ' ', null, 'พเนต', 1234, null, null);
INSERT INTO "Employee" VALUES (9, 1, 'คุณ', 'Administrator', ' -', null, null, null, ' ', null, 'Administrator', 1234, null, null);
INSERT INTO "Employee" VALUES (10, 2, 'คุณ', 'ชวดล', 'พรายทอง', null, null, null, '08-5111-6769', null, 'ชวดล', 1234, null, null);
INSERT INTO "Employee" VALUES (11, 2, 'คุณ', 'ณรงค์', 'ประสพแก้ว', null, null, null, '08-5111-6770', null, 'ณรงค์', 1234, null, null);
INSERT INTO "Employee" VALUES (12, 2, 'คุณ', 'สุระใจ', 'อ่อนอำไพ', null, null, null, '08-5111-6771', null, 'สุระใจ', 1234, null, null);
INSERT INTO "Employee" VALUES (13, 2, 'คุณ', 'ชาญศิริ', 'ศิริทศางค์ชัย', null, null, null, ' ', null, 'ชาญศิริ', 1234, null, null);
INSERT INTO "Employee" VALUES (14, 2, 'คุณ', 'อภิชัย', 'จันทร์ปัญญา', null, null, null, ' ', null, 'อภิชัย', 1234, null, null);
INSERT INTO "Employee" VALUES (15, 2, 'คุณ', 'รัชกร', 'สุวรรณทัต', null, null, null, ' ', null, 'รัชกร', 1234, null, null);
INSERT INTO "Employee" VALUES (16, 2, 'คุณ', 'บุญวิชญ์', 'สร้อยสวัสดิ์', null, null, null, ' ', null, 'บุญวิชญ์', 1234, null, null);
INSERT INTO "Employee" VALUES (17, 2, 'คุณ', 'สิทธิพงศ์', 'เติมทรัพย์วงศ์', null, null, null, '08-5111-6774', null, 'สิทธิพงศ์', 1234, null, null);
INSERT INTO "Employee" VALUES (18, 2, 'คุณ', 'พีรวิชช์', 'แก่นกระจ่าง', null, null, null, ' ', null, 'พีรวิชช์', 1234, null, null);
INSERT INTO "Employee" VALUES (28, 5, 'คุณ', 'ชวนะ', 'วงศ์สหาก', null, null, null, ' ', null, 'ชวนะ', 1234, null, null);
INSERT INTO "Employee" VALUES (29, 2, 'คุณ', 'ธิติกร', 'ธีระกุล', null, null, null, ' ', null, 'ธิติกร', 1234, null, null);
INSERT INTO "Employee" VALUES (30, 2, 'คุณ', 'จิรวุฒิ', 'บุษดี', null, null, null, '08-5111-6776', null, 'จิรวุฒิ', 1234, null, null);
INSERT INTO "Employee" VALUES (31, 2, 'คุณ', 'วรงค์', 'ธารีลาภ', null, null, null, ' ', null, 'วรงค์', 1234, null, null);
INSERT INTO "Employee" VALUES (32, 2, 'คุณ', 'สิทธิรัตน์', 'พันธุ์ไพโรจน์', null, null, null, ' ', null, 'สิทธิรัตน์', 1234, null, null);
INSERT INTO "Employee" VALUES (33, 2, 'คุณ', 'ปฐมพร', 'เหล่าเพชรรัตน์', null, null, null, ' ', null, 'ปฐมพร', 1234, null, null);
INSERT INTO "Employee" VALUES (34, 2, 'คุณ', 'ฉัตรชัย', 'จันทรักษา', null, null, null, ' ', null, 'ฉัตรชัย', 1234, null, null);
INSERT INTO "Employee" VALUES (35, 2, 'คุณ', 'ธัชชัย', 'ดูวิเศษ', null, null, null, '08-5111-6775', null, 'ธัชชัย', 1234, null, null);
INSERT INTO "Employee" VALUES (36, 2, 'คุณ', 'ชายคริสต์', 'รัตฐนันท์ชัย', null, null, null, ' ', null, 'ชายคริสต์', 1234, null, null);
INSERT INTO "Employee" VALUES (38, 2, 'คุณ', 'ศักดา', 'จันดาวงศ์', null, null, null, '08-5111-6750', null, 'ศักดา', 1234, null, null);
INSERT INTO "Employee" VALUES (39, 2, 'คุณ', 'เนวิน', 'การศักดิ์', null, null, null, ' ', null, 'เนวิน', 1234, null, null);
INSERT INTO "Employee" VALUES (40, 2, 'คุณ', 'จิตรกร', 'ผูกพาณิช', null, null, null, ' ', null, 'จิตรกร', 1234, null, null);
INSERT INTO "Employee" VALUES (41, 2, 'คุณ', 'โชคชัย', 'หนูวงศ์', null, null, null, ' ', null, 'โชคชัย', 1234, null, null);
INSERT INTO "Employee" VALUES (42, 2, 'คุณ', 'ประทีป', 'สีดา', null, null, null, '08-5111-6751', null, 'ประทีป', 1234, null, null);
INSERT INTO "Employee" VALUES (43, 5, 'คุณ', 'มนชัย', 'เทียนอร่าม', null, null, null, '08-5111-6752', null, 'มนชัย', 1234, null, null);
INSERT INTO "Employee" VALUES (44, 2, 'คุณ', 'อำพล', 'ศรีนวลจันทร์', null, null, null, '08-5111-6753', null, 'อำพล', 1234, null, null);
INSERT INTO "Employee" VALUES (45, 2, 'คุณ', 'ไพบูลย์', 'ศรีทรงผล', null, null, null, '08-5111-6754', null, 'ไพบูลย์', 1234, null, null);
INSERT INTO "Employee" VALUES (46, 2, 'คุณ', 'ภาคภูมิ', 'โสงขุนทด', null, null, null, '08-5111-6755', null, 'ภาคภูมิ', 1234, null, null);
INSERT INTO "Employee" VALUES (47, 2, 'คุณ', 'ปฏิภาร', 'น้อยผาง', null, null, null, '08-5111-6756', null, 'ปฏิภาร', 1234, null, null);
INSERT INTO "Employee" VALUES (48, 2, 'คุณ', 'วันชัย', 'ฝ่ายดี', null, null, null, '08-5111-6757', null, 'วันชัย', 1234, null, null);
INSERT INTO "Employee" VALUES (49, 2, 'คุณ', 'พัฒนา', 'แก้วมณี', null, null, null, '08-5111-6758', null, 'พัฒนา', 1234, null, null);
INSERT INTO "Employee" VALUES (50, 2, 'คุณ', 'ถวิน', 'ทิศลังกา', null, null, null, ' ', null, 'ถวิน', 1234, null, null);
INSERT INTO "Employee" VALUES (51, 2, 'คุณ', 'เฉลิมพล', 'จันต๊ะวงศ์', null, null, null, '08-5111-6759', null, 'เฉลิมพล', 1234, null, null);
INSERT INTO "Employee" VALUES (52, 2, 'คุณ', 'นัฐพงษ์', 'พงศ์พุฒิ', null, null, null, ' ', null, 'นัฐพงษ์', 1234, null, null);
INSERT INTO "Employee" VALUES (53, 2, 'คุณ', 'สมควร', 'สมประสงค์', null, null, null, '08-5111-8858', null, 'สมควร', 1234, null, null);
INSERT INTO "Employee" VALUES (54, 2, 'คุณ', 'นนทพัฒน์', 'นาคมโน', null, null, null, ' ', null, 'นนทพัฒน์', 1234, null, null);
INSERT INTO "Employee" VALUES (55, 2, 'คุณ', 'อุดร', 'สุภิรับ', null, null, null, '08-5111-6760', null, 'อุดร', 1234, null, null);
INSERT INTO "Employee" VALUES (56, 2, 'คุณ', 'สันติ', 'สุอาราม', null, null, null, '08-5111-6761', null, 'สันติ', 1234, null, null);
INSERT INTO "Employee" VALUES (57, 2, 'คุณ', 'จักรพันธ์', 'จันต๊ะมา', null, null, null, '08-5111-6762', null, 'จักรพันธ์', 1234, null, null);
INSERT INTO "Employee" VALUES (58, 2, 'คุณ', 'ศุภณัฐ', 'เรืองอ่อง', null, null, null, '08-5111-8856', null, 'ศุภณัฐ', 1234, null, null);
INSERT INTO "Employee" VALUES (60, 2, 'คุณ', 'ประยงค์', 'ดอนเสนา', null, null, null, '08-5111-8857', null, 'ประยงค์', 1234, null, null);
INSERT INTO "Employee" VALUES (61, 2, 'คุณ', 'ธนา', 'รัตนเสถียร', null, null, null, ' ', null, 'ธนา', 1234, null, null);
INSERT INTO "Employee" VALUES (62, 2, 'คุณ', 'กฤษฏา', 'พุกเถื่อน', null, null, null, '', null, 'กฤษฏา', 1234, null, null);
INSERT INTO "Employee" VALUES (63, 2, 'คุณ', 'สราวุธ', 'เซ็นเชาวนิช', null, null, null, '', null, 'สราวุธ', 1234, null, null);
INSERT INTO "Employee" VALUES (64, 2, 'คุณ', 'สกุลวุฒิ', 'วุฒิยากร', null, null, null, '', null, 'สกุลวุฒิ', 1234, null, null);
INSERT INTO "Employee" VALUES (65, 2, 'คุณ', 'กิตติภูมิ', 'สินนะคำ', null, null, null, '', null, 'กิตติภูมิ', 1234, null, null);
INSERT INTO "Employee" VALUES (66, 2, 'คุณ', 'สมพร', 'ตึกปากเกล็ด', null, null, null, '', null, 'สมพร', 1234, null, null);
INSERT INTO "Employee" VALUES (67, 2, 'คุณ', 'ธีระพล', 'พูดเพราะ', null, null, null, '', null, 'ธีระพล', 1234, null, null);
INSERT INTO "Employee" VALUES (68, 2, 'คุณ', 'อโณทัย', 'ปานทอง', null, null, null, '', null, 'อโณทัย', 1234, null, null);
INSERT INTO "Employee" VALUES (69, 2, 'คุณ', 'รัฐกฤษฎิ์', 'เลิศมงคลจิรากุล', null, null, null, '', null, 'รัฐกฤษฎิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (70, 2, 'คุณ', 'ปรรกร', 'โฆษิตคณิณ', null, null, null, '', null, 'ปรรกร', 1234, null, null);
INSERT INTO "Employee" VALUES (71, 2, 'คุณ', 'ประทรัพย์', 'อุ่นผาง', null, null, null, '', null, 'ประทรัพย์', 1234, null, null);
INSERT INTO "Employee" VALUES (72, 2, 'คุณ', 'วีระพงษ์', 'สาระรัตน์', null, null, null, '', null, 'วีระพงษ์', 1234, null, null);
INSERT INTO "Employee" VALUES (73, 2, 'คุณ', 'ไตรภพ', 'อรรถสิษฐ', null, null, null, '', null, 'ไตรภพ', 1234, null, null);
INSERT INTO "Employee" VALUES (74, 2, 'คุณ', 'สงกรานต์', 'เดียวสุรินทร์', null, null, null, '08-5111-8859', null, 'สงกรานต์', 1234, null, null);
INSERT INTO "Employee" VALUES (75, 2, 'คุณ', 'เลิศศักดิ์', 'ชูทรัพย์', null, null, null, '', null, 'เลิศศักดิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (76, 2, 'คุณ', 'วัชร', 'ขวัญสมคิด', null, null, null, '', null, 'วัชร', 1234, null, null);
INSERT INTO "Employee" VALUES (77, 2, 'คุณ', 'ณัฐวุฒิ', 'ตาชูชาติ', null, null, null, '', null, 'ณัฐวุฒิ', 1234, null, null);
INSERT INTO "Employee" VALUES (78, 2, 'คุณ', 'บริพัตร', 'ปัดแพง', null, null, null, '', null, 'บริพัตร', 1234, null, null);
INSERT INTO "Employee" VALUES (79, 2, 'คุณ', 'ภัคพล', 'สุริยฉาย', null, null, null, '', null, 'ภัคพล', 1234, null, null);
INSERT INTO "Employee" VALUES (80, 2, 'คุณ', 'ธีรศักดิ์', 'มุสตอฟาดี', null, null, null, '', null, 'ธีรศักดิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (81, 2, 'คุณ', 'อนุสรณ์', 'พานิชนก', null, null, null, '', null, 'อนุสรณ์', 1234, null, null);
INSERT INTO "Employee" VALUES (82, 2, 'คุณ', 'สุรศักดิ์', 'ไชยราช', null, null, null, '', null, 'สุรศักดิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (83, 2, 'คุณ', 'ปฏิวัติ', 'แก้วเบ้า', null, null, null, '', null, 'ปฏิวัติ', 1234, null, null);
INSERT INTO "Employee" VALUES (84, 2, 'คุณ', 'ธนพล', 'นุ่มมีศรี', null, null, null, '', null, 'ธนพล', 1234, null, null);
INSERT INTO "Employee" VALUES (85, 2, 'คุณ', 'สุทธิลักษณ์', 'จงกลศรี', null, null, null, '', null, 'สุทธิลักษณ์', 1234, null, null);
INSERT INTO "Employee" VALUES (86, 2, 'คุณ', 'ดุสิต', 'ดียิ่ง', null, null, null, '', null, 'ดุสิต', 1234, null, null);
INSERT INTO "Employee" VALUES (87, 2, 'คุณ', 'ภานุวัฒน์', 'พันพั่ว', null, null, null, '', null, 'ภานุวัฒน์', 1234, null, null);
INSERT INTO "Employee" VALUES (88, 2, 'คุณ', 'อำนาจ', 'บัวสุวรรณ', null, null, null, '', null, 'อำนาจ', 1234, null, null);
INSERT INTO "Employee" VALUES (89, 2, 'คุณ', 'จักรกริช', 'อุ่นสกล', null, null, null, '', null, 'จักรกริช', 1234, null, null);
INSERT INTO "Employee" VALUES (91, 2, 'คุณ', 'ณัฐนันท์', 'นิสังรัมย์', null, null, null, '', null, 'ณัฐนันท์', 1234, null, null);
INSERT INTO "Employee" VALUES (92, 2, 'คุณ', 'สัมพันธ์', 'ตันวงศ์', null, null, null, '', null, 'สัมพันธ์', 1234, null, null);
INSERT INTO "Employee" VALUES (93, 2, 'คุณ', 'นครินทร์', 'แก้วจันทร์', null, null, null, '', null, 'นครินทร์', 1234, null, null);
INSERT INTO "Employee" VALUES (94, 2, 'คุณ', 'ธนิศร์', 'เอี่ยมสุวรรณ', null, null, null, '', null, 'ธนิศร์', 1234, null, null);
INSERT INTO "Employee" VALUES (95, 2, 'คุณ', 'ศรัณยู', 'เพ็ชรพราว', null, null, null, '', null, 'ศรัณยู', 1234, null, null);
INSERT INTO "Employee" VALUES (96, 2, 'คุณ', 'มงคล', 'บุตรดาวงษ์', null, null, null, '', null, 'มงคล', 1234, null, null);
INSERT INTO "Employee" VALUES (97, 2, 'คุณ', 'มนตรี', 'อยู่ยิ่ง', null, null, null, '', null, 'มนตรี', 1234, null, null);
INSERT INTO "Employee" VALUES (98, 2, 'คุณ', 'อภิวัฒน์', 'เพ็ชรจิตร์', null, null, null, '', null, 'อภิวัฒน์', 1234, null, null);
INSERT INTO "Employee" VALUES (99, 2, 'คุณ', 'รัฐพงษ์', 'จันมา', null, null, null, '', null, 'รัฐพงษ์', 1234, null, null);
INSERT INTO "Employee" VALUES (100, 2, 'คุณ', 'ปวีนา', 'เชื้อแก้ว', null, null, null, '', null, 'ปวีนา', 1234, null, null);
INSERT INTO "Employee" VALUES (101, 2, 'คุณ', 'ธนาฒย์', 'พลอาวุธ', null, null, null, '', null, 'ธนาฒย์', 1234, null, null);
INSERT INTO "Employee" VALUES (102, 2, 'คุณ', 'ปัญญา', 'พานมั่ง', null, null, null, '', null, 'ปัญญา', 1234, null, null);
INSERT INTO "Employee" VALUES (103, 2, 'คุณ', 'ดนุพล', 'สีนารักษ์', null, null, null, '', null, 'ดนุพล', 1234, null, null);
INSERT INTO "Employee" VALUES (104, 2, 'คุณ', 'ศรัทธา', 'อยู่สุธา', null, null, null, '', null, 'ศรัทธา', 1234, null, null);
INSERT INTO "Employee" VALUES (105, 2, 'คุณ', 'สุคเชนทร์', 'ด่านกุล', null, null, null, '', null, 'สุคเชนทร์', 1234, null, null);
INSERT INTO "Employee" VALUES (106, 2, 'คุณ', 'สุรสิทธิ์', 'มะโนนำ', null, null, null, '', null, 'สุรสิทธิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (107, 2, 'คุณ', 'สุชิน', 'รุ่งเรืองยั่งยืน', null, null, null, '', null, 'สุชิน', 1234, null, null);
INSERT INTO "Employee" VALUES (109, 2, 'คุณ', 'บัณฑิต', 'จินาพันธ์', null, null, null, '', null, 'บัณฑิต', 1234, null, null);
INSERT INTO "Employee" VALUES (110, 2, 'คุณ', 'เอกวิทย์', 'วันทองสุข', null, null, null, '', null, 'เอกวิทย์', 1234, null, null);
INSERT INTO "Employee" VALUES (111, 2, 'คุณ', 'ทรงวุฒิ', 'ไชยปัญญา', null, null, null, '', null, 'ทรงวุฒิ', 1234, null, null);
INSERT INTO "Employee" VALUES (112, 2, 'คุณ', 'สามารถ', 'อ่อนเอี่ยม', null, null, null, '', null, 'สามารถ', 1234, null, null);
INSERT INTO "Employee" VALUES (113, 2, 'คุณ', 'นพพร', 'เจริญทรัพย์', null, null, null, '', null, 'นพพร', 1234, null, null);
INSERT INTO "Employee" VALUES (114, 2, 'คุณ', 'เอกพันธ์', 'ปัญญาใจ', null, null, null, '', null, 'เอกพันธ์', 1234, null, null);
INSERT INTO "Employee" VALUES (115, 2, 'คุณ', 'นรากร', 'เวียงทอง', null, null, null, '', null, 'นรากร', 1234, null, null);
INSERT INTO "Employee" VALUES (116, 2, 'คุณ', 'กิติชัย', 'เรืองบุญธรรม', null, null, null, '', null, 'กิติชัย', 1234, null, null);
INSERT INTO "Employee" VALUES (117, 2, 'คุณ', 'ชูศักดิ์', 'มีอนันต์', null, null, null, '', null, 'ชูศักดิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (118, 2, 'คุณ', 'สรรค์ธกรณ์', 'เอกวิบูลสถิตย์', null, null, null, '', null, 'สรรค์ธกรณ์', 1234, null, null);
INSERT INTO "Employee" VALUES (119, 2, 'คุณ', 'ยศธนา', 'พามอก', null, null, null, '', null, 'ยศธนา', 1234, null, null);
INSERT INTO "Employee" VALUES (121, 2, 'คุณ', 'วรวุฒิ', 'คุณป๊อก', null, null, null, '', null, 'วรวุฒิ', 1234, null, null);
INSERT INTO "Employee" VALUES (122, 2, 'คุณ', 'อาทิตย์', 'กันน้อย', null, null, null, '', null, 'อาทิตย์', 1234, null, null);
INSERT INTO "Employee" VALUES (123, 2, 'คุณ', 'คมสันต์', 'หยวกเดช', null, null, null, '', null, 'คมสันต์', 1234, null, null);
INSERT INTO "Employee" VALUES (124, 2, 'คุณ', 'ณรงค์ชัย', 'ไชยคำ', null, null, null, '', null, 'ณรงค์ชัย', 1234, null, null);
INSERT INTO "Employee" VALUES (125, 2, 'คุณ', 'ชัยยัณต์', 'สืบเสาะเสมอ', null, null, null, '', null, 'ชัยยัณต์', 1234, null, null);
INSERT INTO "Employee" VALUES (126, 2, 'คุณ', 'วรวิทย์', 'วงษ์ชัยเพ็ง', null, null, null, '', null, 'วรวิทย์', 1234, null, null);
INSERT INTO "Employee" VALUES (127, 2, 'คุณ', 'นพดล', 'ชื่นเลิศสกุล', null, null, null, '', null, 'นพดล', 1234, null, null);
INSERT INTO "Employee" VALUES (129, 2, 'คุณ', 'มงคลชัย', 'กันเพ็ง', null, null, null, '', null, 'มงคลชัย', 1234, null, null);
INSERT INTO "Employee" VALUES (130, 2, 'คุณ', 'รัตตภูมิ', 'ปินะเล', null, null, null, '', null, 'รัตตภูมิ', 1234, null, null);
INSERT INTO "Employee" VALUES (131, 2, 'คุณ', 'วุฒิพงษ์', 'ผาภู', null, null, null, '', null, 'วุฒิพงษ์', 1234, null, null);
INSERT INTO "Employee" VALUES (132, 2, 'คุณ', 'วีระกร', 'ธโนปจัย', null, null, null, '', null, 'วีระกร', 1234, null, null);
INSERT INTO "Employee" VALUES (133, 2, 'คุณ', 'ผาณุ', 'สืบเมือง', null, null, null, '', null, 'ผาณุ', 1234, null, null);
INSERT INTO "Employee" VALUES (134, 2, 'คุณ', 'ชูชาติ', 'รื่นรส', null, null, null, '', null, 'ชูชาติ', 1234, null, null);
INSERT INTO "Employee" VALUES (135, 2, 'คุณ', 'นิพันธ์', 'บุตรนัย', null, null, null, '', null, 'นิพันธ์', 1234, null, null);
INSERT INTO "Employee" VALUES (136, 2, 'คุณ', 'ชานนท์', 'จำปานิล', null, null, null, '', null, 'ชานนท์', 1234, null, null);
INSERT INTO "Employee" VALUES (137, 2, 'คุณ', 'เวทิน', 'พลมะศรี', null, null, null, '', null, 'เวทิน', 1234, null, null);
INSERT INTO "Employee" VALUES (138, 2, 'คุณ', 'สมดุลย์', 'หีบท่าไม้', null, null, null, '', null, 'สมดุลย์', 1234, null, null);
INSERT INTO "Employee" VALUES (140, 2, 'คุณ', 'อัมพล', 'สงกรานต์เสงี่ยม', null, null, null, '', null, 'อัมพล', 1234, null, null);
INSERT INTO "Employee" VALUES (141, 2, 'คุณ', 'จตุพร', 'ดวงธนู', null, null, null, '', null, 'จตุพร', 1234, null, null);
INSERT INTO "Employee" VALUES (142, 2, 'คุณ', 'คมสันติ์', 'ทาคำ', null, null, null, '', null, 'คมสันติ์', 1234, null, null);
INSERT INTO "Employee" VALUES (143, 2, 'คุณ', 'ปิยะวัตร', 'เถียรทองศรี', null, null, null, '', null, 'ปิยะวัตร', 1234, null, null);
INSERT INTO "Employee" VALUES (144, 2, 'คุณ', 'บุญมาก', 'วิศรุตเวสสะภู', null, null, null, '', null, 'บุญมาก', 1234, null, null);
INSERT INTO "Employee" VALUES (145, 2, 'คุณ', 'ธานินทร์', 'เข็มทอง', null, null, null, '', null, 'ธานินทร์', 1234, null, null);
INSERT INTO "Employee" VALUES (146, 2, 'คุณ', 'สุภวัฒน์', 'มาดี', null, null, null, '', null, 'สุภวัฒน์', 1234, null, null);
INSERT INTO "Employee" VALUES (147, 2, 'คุณ', 'ทรงพล', 'หม่องอ้น', null, null, null, '', null, 'ทรงพล', 1234, null, null);
INSERT INTO "Employee" VALUES (148, 2, 'คุณ', 'ศิวะพร', 'อินทรนิมิตร', null, null, null, '', null, 'ศิวะพร', 1234, null, null);
INSERT INTO "Employee" VALUES (149, 2, 'คุณ', 'วชิรพงศ์ ', 'เวียงใต้', null, null, null, '', null, 'วชิรพงศ์ ', 1234, null, null);
INSERT INTO "Employee" VALUES (150, 2, 'คุณ', 'ปฐมพงษ์ ', 'ปะระตะโก', null, null, null, '', null, 'ปฐมพงษ์ ', 1234, null, null);
INSERT INTO "Employee" VALUES (151, 2, 'คุณ', 'กฤษดา', 'ไกรศิลล์', null, null, null, '', null, 'กฤษดา', 1234, null, null);
INSERT INTO "Employee" VALUES (152, 2, 'คุณ', 'ธิติ', 'ธนาพงศธร', null, null, null, '', null, 'ธิติ', 1234, null, null);
INSERT INTO "Employee" VALUES (153, 2, 'คุณ', 'ศุภชัย', 'ผลปาน', null, null, null, '', null, 'ศุภชัย', 1234, null, null);
INSERT INTO "Employee" VALUES (154, 2, 'คุณ', 'อาณัติ', 'สิงห์สังข์', null, null, null, '', null, 'อาณัติ', 1234, null, null);
INSERT INTO "Employee" VALUES (155, 2, 'คุณ', 'เกียรติศักดิ์', 'สาระคำ', null, null, null, '', null, 'เกียรติศักดิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (156, 2, 'คุณ', 'ธนัท', 'เจริญด้วงรักษา', null, null, null, '', null, 'ธนัท', 1234, null, null);
INSERT INTO "Employee" VALUES (157, 2, 'คุณ', 'วีรศักดิ์', 'สีลาเหลี่ยม', null, null, null, '', null, 'วีรศักดิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (158, 2, 'คุณ', 'จักรพงษ์', 'ลีกวี', null, null, null, '', null, 'จักรพงษ์', 1234, null, null);
INSERT INTO "Employee" VALUES (159, 2, 'คุณ', 'พงศักดิ์', 'บุญเพ็ง', null, null, null, '', null, 'พงศักดิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (160, 2, 'คุณ', 'มนัส', 'อินทวินัย', null, null, null, '', null, 'มนัส', 1234, null, null);
INSERT INTO "Employee" VALUES (161, 2, 'คุณ', 'วรยุทธ', 'จันทบาล', null, null, null, '', null, 'วรยุทธ', 1234, null, null);
INSERT INTO "Employee" VALUES (163, 2, 'คุณ', 'ธีระ', 'มีบุญพูลทรัพย์', null, null, null, '', null, 'ธีระ', 1234, null, null);
INSERT INTO "Employee" VALUES (164, 2, 'คุณ', 'ยุทธนา', 'เกตุแก้ว', null, null, null, '', null, 'ยุทธนา', 1234, null, null);
INSERT INTO "Employee" VALUES (165, 2, 'คุณ', 'พลวัฒน์', 'สิงห์นุช', null, null, null, '', null, 'พลวัฒน์', 1234, null, null);
INSERT INTO "Employee" VALUES (166, 2, 'คุณ', 'อนุวัฒน์', 'หลีจาง', null, null, null, '', null, 'อนุวัฒน์', 1234, null, null);
INSERT INTO "Employee" VALUES (167, 2, 'คุณ', 'คุณากร', 'เกียรติขจรไพศาล', null, null, null, '', null, 'คุณากร', 1234, null, null);
INSERT INTO "Employee" VALUES (168, 2, 'คุณ', 'วรากร', 'วงศ์ปิน', null, null, null, '', null, 'วรากร', 1234, null, null);
INSERT INTO "Employee" VALUES (169, 2, 'คุณ', 'อธิปพันธ์', 'รักษาพงษ์', null, null, null, '', null, 'อธิปพันธ์', 1234, null, null);
INSERT INTO "Employee" VALUES (170, 2, 'คุณ', 'อานนท์', 'คล้ำประเสริฐ', null, null, null, '', null, 'อานนท์', 1234, null, null);
INSERT INTO "Employee" VALUES (171, 2, 'คุณ', 'ธีรพัฒน์', 'อภิชาติ', null, null, null, '', null, 'ธีรพัฒน์', 1234, null, null);
INSERT INTO "Employee" VALUES (173, 2, 'คุณ', 'นฤพงษ์', 'ทองรัก', null, null, null, '', null, 'นฤพงษ์', 1234, null, null);
INSERT INTO "Employee" VALUES (174, 2, 'คุณ', 'วรวิท', 'สมยิ่ง', null, null, null, '', null, 'วรวิท', 1234, null, null);
INSERT INTO "Employee" VALUES (175, 2, 'คุณ', 'ปรีชา', 'ชมพูประเภท', null, null, null, '', null, 'ปรีชา', 1234, null, null);
INSERT INTO "Employee" VALUES (176, 2, 'คุณ', 'ณัฐพล', 'วงศ์ไชย', null, null, null, '', null, 'ณัฐพล', 1234, null, null);
INSERT INTO "Employee" VALUES (177, 2, 'คุณ', 'ยืนยง', 'วงศ์บุญชัยเลิศ', null, null, null, '', null, 'ยืนยง', 1234, null, null);
INSERT INTO "Employee" VALUES (178, 2, 'คุณ', 'วิทยา ', 'เจริญรัมย์ ', null, null, null, '', null, 'วิทยา ', 1234, null, null);
INSERT INTO "Employee" VALUES (179, 2, 'คุณ', 'ตระกูลศักดิ์', 'จันตะคุณ', null, null, null, '', null, 'ตระกูลศักดิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (180, 2, 'คุณ', 'สิทธินันท์', 'เอื้อกิจ', null, null, null, '', null, 'สิทธินันท์', 1234, null, null);
INSERT INTO "Employee" VALUES (181, 2, 'คุณ', 'ประมวล', 'อัปมะเย', null, null, null, '', null, 'ประมวล', 1234, null, null);
INSERT INTO "Employee" VALUES (182, 2, 'คุณ', 'ยุทธเกียรติ', 'ลาภาอุตม์', null, null, null, '', null, 'ยุทธเกียรติ', 1234, null, null);
INSERT INTO "Employee" VALUES (183, 2, 'คุณ', 'สมพล', 'พุทธเสน', null, null, null, '', null, 'สมพล', 1234, null, null);
INSERT INTO "Employee" VALUES (184, 2, 'คุณ', 'ยุทธศักดิ์', 'จันทร์กลิ่น', null, null, null, '', null, 'ยุทธศักดิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (185, 2, 'คุณ', 'นิกร', 'ศรีเที่ยง', null, null, null, '', null, 'นิกร', 1234, null, null);
INSERT INTO "Employee" VALUES (186, 2, 'คุณ', 'นฤพล', 'บุญสุข', null, null, null, '', null, 'นฤพล', 1234, null, null);
INSERT INTO "Employee" VALUES (187, 2, 'คุณ', 'สุวิทย์', 'ชัยศิริชัยยะ', null, null, null, '', null, 'สุวิทย์', 1234, null, null);
INSERT INTO "Employee" VALUES (188, 2, 'คุณ', 'ประสิทธิ์', 'โนนกลาง', null, null, null, '', null, 'ประสิทธิ์', 1234, null, null);
INSERT INTO "Employee" VALUES (189, 2, 'คุณ', 'ธัญญะ', 'ม่วงมนตรี', null, null, null, '', null, 'ธัญญะ', 1234, null, null);
INSERT INTO "Employee" VALUES (191, 2, 'คุณ', 'สุทธิพล', 'ศรีโสมาตย์', null, null, null, '', null, 'สุทธิพล', 1234, null, null);
INSERT INTO "Employee" VALUES (192, 2, 'คุณ', 'อุทัย', 'ใจดี', null, null, null, '', null, 'อุทัย', 1234, null, null);
INSERT INTO "Employee" VALUES (196, 1, 'คุณ', 'มณฑาทิพย์', 'เกื้อกอบ', null, null, null, '', null, 'มณฑาทิพย์', 1234, null, null);
INSERT INTO "Employee" VALUES (197, 3, 'คุณ', 'ธมลชนก', 'แสงประทีปทอง', null, null, null, '', null, 'ธมลชนก', 1234, null, null);
INSERT INTO "Employee" VALUES (198, 3, 'คุณ', 'แพรไพลิน', 'เกิดผล', null, null, null, '', null, 'แพรไพลิน', 1234, null, null);
INSERT INTO "Employee" VALUES (201, 5, 'คุณ', 'รัชพล', 'ผดุงทอง', null, null, null, '', null, 'รัชพล', 1234, null, null);
INSERT INTO "Employee" VALUES (203, 4, 'คุณ', 'สุรพล', 'เมฆตะวันฉาย', null, null, null, '', null, 'สุรพล', 1234, null, null);
INSERT INTO "Employee" VALUES (223, 3, 'คุณ', 'วรัทยา', 'แสงน้อย', null, null, null, '', null, 'วรัทยา', 1234, null, null);


INSERT INTO "EmpAssignedInTeam" VALUES (1, 1, 1);

INSERT INTO "ExpenseType" VALUES(1,'ตรวจสินค้า');
INSERT INTO "ExpenseType" VALUES(2,'อบรม');
INSERT INTO "ExpenseType" VALUES(3,'ย้ายสาย');

INSERT INTO ReasonSentence(reasonSentenceType,reasonSentenceText) VALUES(0,'ลูกค้าแจ้งว่ายังไม่ใช้วงเงิน');
INSERT INTO ReasonSentence(reasonSentenceType,reasonSentenceText) VALUES(0,'ลูกค้าแจ้งว่ายกเลิกวงเงินธนาคารแล้ว');
INSERT INTO ReasonSentence(reasonSentenceType,reasonSentenceText) VALUES(0,'สถานที่เก็บสินค้าประสบเหตุอุทกภัย');
INSERT INTO ReasonSentence(reasonSentenceType,reasonSentenceText) VALUES(0,'สถานที่เก็บสินค้าประสบเหตุวาตภัย');
INSERT INTO ReasonSentence(reasonSentenceType,reasonSentenceText) VALUES(1,'ลูกค้าอยู่ระหว่างใช้สถานที่ในงานพิธี');
INSERT INTO ReasonSentence(reasonSentenceType,reasonSentenceText) VALUES(1,'ลูกค้าติดธุระไม่สามารถเดินทางมาเปิดสถานที่เก็บสินค้าได้');
INSERT INTO ReasonSentence(reasonSentenceType,reasonSentenceText) VALUES(1,'ลูกค้าหยุดกิจการตามเทศกาลและประเพณีท้องถิ่น');
INSERT INTO ReasonSentence(reasonSentenceType,reasonSentenceText) VALUES(1,'ลูกค้าได้จำหน่ายสินค้าไปหมดแล้ว');

INSERT INTO MarketPrice VALUES (1,1,1,100);
INSERT INTO MarketPrice VALUES (1,1,2,200);
